services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # porta de comunicacao com rabbitmq
      - "15672:15672"
      - "15692:15692" # porta facilita navegacao no admin rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/